/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-11-15 03:10:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.customer._02_menu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import paik_prj.paik_prj.customer.paik.CustomVO;
import java.util.ArrayList;
import java.util.Random;
import java.util.List;
import paik_prj.paik_prj.customer.paik.ItemDAO;
import paik_prj.paik_prj.customer.paik.ItemVO;

public final class drinkMenuPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "메뉴 - 음료 페이지";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/web_home/paik_prj/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1729132892000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("paik_prj.paik_prj.customer.paik.CustomVO");
    _jspx_imports_classes.add("java.util.Random");
    _jspx_imports_classes.add("paik_prj.paik_prj.customer.paik.ItemDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("paik_prj.paik_prj.customer.paik.ItemVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/customer/05.mypage/remove_password_verified.jsp", out, false);
      out.write('\r');
      out.write('\n');
      paik_prj.paik_prj.customer.paik.ItemVO iVO = null;
      iVO = (paik_prj.paik_prj.customer.paik.ItemVO) _jspx_page_context.getAttribute("iVO", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (iVO == null){
        iVO = new paik_prj.paik_prj.customer.paik.ItemVO();
        _jspx_page_context.setAttribute("iVO", iVO, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("iVO"), request);
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko-KR\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"http://paiks.sist.co.kr/customer/00.common/images/btnImg.png\">\r\n");
      out.write("\r\n");
      out.write("<title>빽스커피 | 음료</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://paiks.sist.co.kr/customer/02.menu/css/paik_menu.css\">\r\n");
      out.write("<link rel=\"stylesheet\" id=\"theme-css-style-css\"  href=\"https://paikdabang.com/wp-content/themes/paikdabang/assets/css/style.css?ver=4.9.4\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"icon\" href=\"http://paiks.sist.co.kr/customer/00.common/images/favicon32x32.png\" sizes=\"32x32\" />\r\n");
      out.write("<link rel=\"icon\" href=\"http://paiks.sist.co.kr/customer/00.common/images/favicon192x192.png\" sizes=\"192x192\" />\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" href=\"http://paiks.sist.co.kr/customer/00.common/images/favicon180x180.png\" />\r\n");
      out.write("<meta name=\"msapplication-TileImage\" content=\"http://paiks.sist.co.kr/customer/00.common/images/favicon270x270.png\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://unpkg.com/swiper/swiper-bundle.min.css\">\r\n");
      out.write("<script src=\"https://unpkg.com/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("\r\n");

	CustomVO userData = (CustomVO)session.getAttribute("userData");

      out.write("\r\n");
      out.write("<script src=\"http://paiks.sist.co.kr/customer/02.menu/jsp/menu.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var loginFlag = ");
      out.print( (userData != null) ? "true" : "false" );
      out.write(";\r\n");
      out.write("//console.log(loginFlag);\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("	\r\n");
      out.write("});//ready()\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("<div id=\"header\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/customer/00.common/jsp/header.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

	ItemDAO iDAO = ItemDAO.getInstance();
	List<ItemVO> drinkItems = iDAO.selectMainItem(1);	//1 - 음료
	
	Random ranItem = new Random();
	int selectItemRan = Math.min(5, drinkItems.size());	//최대 5개의
	List<Integer> selectInd = new ArrayList<Integer>();
	
	while(selectInd.size()<selectItemRan){
		int ranInd = ranItem.nextInt(drinkItems.size());
		if(!selectInd.contains(ranInd)){
			selectInd.add(ranInd);
		}//if
	}//w

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"content-wrap\">\r\n");
      out.write("<div class=\"sub_visual bg-menu3\">\r\n");
      out.write("	<div class=\"txt\">\r\n");
      out.write("		<h1>음료</h1>\r\n");
      out.write("		<p>퀄리티 높은 식자재를 사용해 맛있는 음료를 제공합니다.</p>\r\n");
      out.write("		<div class=\"tabMenu\">\r\n");
      out.write("			<ul class=\"pageTab\">\r\n");
      out.write("				<li><a href=\"http://paiks.sist.co.kr/customer/02.menu/newMenuPage.jsp\">신메뉴</a></li>\r\n");
      out.write("				<li><a href=\"http://paiks.sist.co.kr/customer/02.menu/coffeeMenuPage.jsp\">커피</a></li>\r\n");
      out.write("				<li class=\"on\"><a href=\"http://paiks.sist.co.kr/customer/02.menu/drinkMenuPage.jsp\">음료</a></li>\r\n");
      out.write("				<li><a href=\"http://paiks.sist.co.kr/customer/02.menu/icecreamDessertMenuPage.jsp\">아이스크림/디저트</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"sub_section menu_wrap\">\r\n");
      out.write("	<div class=\"mainContainer\">\r\n");
      out.write("		<h2 class=\"main_tit3 color-1\">추천메뉴</h2>\r\n");
      out.write("		<div class=\"swiper-container\">\r\n");
      out.write("			<div class=\"swiper-wrapper\">\r\n");
      out.write("				");

				for(int i=0; i<selectInd.size(); i++){
					int ind = selectInd.get(i);
					ItemVO item = drinkItems.get(ind);
				
      out.write("\r\n");
      out.write("				<div class=\"swiper-slide\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li data-item-num=\"");
      out.print( item.getItemNum());
      out.write("\">\r\n");
      out.write("							<img src=\"");
      out.print( item.getImage() );
      out.write("\" class=\"menuItem\" />\r\n");
      out.write("							<p><strong>");
      out.print( item.getiNameKor() );
      out.write("</strong></p>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				");
 }//f 
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"swiper-button-next\" style=\"position: absolute; top: 30%;\"></div>\r\n");
      out.write("			<div class=\"swiper-button-prev\" style=\"position: absolute; top: 30%;\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"menuList\">\r\n");
      out.write("			<ul class=\"menuItems\">\r\n");
      out.write("				");
 for(ItemVO item : drinkItems){
						if(item.getItemFlag() == 'N'){
							//System.out.println(item.getItemNum() + " / " + item.getiNameKor());	//확인용
				
      out.write("\r\n");
      out.write("				<li data-item-num=\"");
      out.print( item.getItemNum());
      out.write("\">\r\n");
      out.write("					<img src=\"");
      out.print( item.getImage() );
      out.write("\" class=\"menuItem\" />\r\n");
      out.write("					<p><strong>");
      out.print( item.getiNameKor() );
      out.write("</strong></p>\r\n");
      out.write("				</li>\r\n");
      out.write("				");
 		}//if
					}//f 
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"menuInfo\" style=\"display: none;\">\r\n");
      out.write("			<button class=\"closeInfo\">X</button>\r\n");
      out.write("			<h2 class=\"itemName\"></h2>\r\n");
      out.write("			<h4 class=\"itemEngName\"></h4>\r\n");
      out.write("			<p class=\"itemContent\"></p>\r\n");
      out.write("			<div class=\"ingredientsContainer\">\r\n");
      out.write("				<input type=\"button\" class=\"putBtn\" id=\"putBtn\" value=\"담기\"/>\r\n");
      out.write("				<span style=\"font-size: 15px;\">가격: <span class=\"itemPrice\"></span>원</span>\r\n");
      out.write("				<table class=\"ingredientsTable\">\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("			<p></p>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/customer/00.common/jsp/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
