/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-11-15 03:11:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manage.customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import paik_prj.paik_prj.manager.paik.customer.CustomerDAO;
import java.sql.SQLException;
import paik_prj.paik_prj.manager.paik.customer.Grade;
import paik_prj.paik_prj.manager.paik.customer.CustomerVO;
import kr.co.sist.chipher.DataDecryption;

public final class detail_005fcustomer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/web_home/paik_prj/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1729132892000L));
    _jspx_dependants.put("jar:file:/C:/web_home/paik_prj/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/manage/common/jsp/manager_session_chk.jsp", Long.valueOf(1731635522000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("kr.co.sist.chipher.DataDecryption");
    _jspx_imports_classes.add("paik_prj.paik_prj.manager.paik.customer.CustomerVO");
    _jspx_imports_classes.add("paik_prj.paik_prj.manager.paik.customer.CustomerDAO");
    _jspx_imports_classes.add("paik_prj.paik_prj.manager.paik.customer.Grade");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    request.setCharacterEncoding("UTF-8");
    // 현재 접속하고 있는 URL을 저장한다. ( 꼭 리다이렉트 전에 해야함 )
    String currentUrl = request.getRequestURI().toString();
    pageContext.setAttribute("currentUrl", currentUrl);


      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;

    //회원의 아이디를 전달 받는다.
    String cusId = request.getParameter("cusId");

    CustomerDAO cDAO = CustomerDAO.getInstance();

    CustomerVO cVO = null;
    try {
        cVO = cDAO.selectOneCustomer(cusId);
    } catch (SQLException e) {
        e.printStackTrace();
    }

    DataDecryption dd = new DataDecryption("abcdef0123456789");
    pageContext.setAttribute("cVO", cVO);
    pageContext.setAttribute("Grade", Grade.class);
    pageContext.setAttribute("dd", dd);


      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\" data-bs-theme=\"auto\">\r\n");
      out.write("<head><script src=\"/docs/5.3/assets/js/color-modes.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\r\n");
      out.write("    <meta name=\"generator\" content=\"Hugo 0.122.0\">\r\n");
      out.write("    <title>회원 상세보기</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://paiks.sist.co.kr/manage/common/css/project_main.css\">\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"http://paiks.sist.co.kr/manage/common/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"http://paiks.sist.co.kr/manage/common/css/dashboard.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("	<!-- bootstrap -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.0/font/bootstrap-icons.css\" />\r\n");
      out.write("	<!-- SweetAlert -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.4.10/dist/sweetalert2.min.css\">\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.4.10/dist/sweetalert2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery -->\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("	<script src=\"//code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"theme-color\" content=\"#712cf9\">\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("	    body { font-family: Arial, sans-serif; margin: 0; }\r\n");
      out.write("        h1 { margin-bottom: 20px; }\r\n");
      out.write("        form { max-width: 500px; margin: 0 auto; }\r\n");
      out.write("        label { display: block; margin-top: 10px; }\r\n");
      out.write("        input, select { width: 100%; padding: 8px; margin-top: 5px; box-sizing: border-box; }\r\n");
      out.write("        a { text-decoration: none; color: #FFF; }\r\n");
      out.write("\r\n");
      out.write("        .bi {\r\n");
      out.write("            vertical-align: -.125em;\r\n");
      out.write("            fill: currentColor;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-scroller .nav {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-wrap: nowrap;\r\n");
      out.write("            padding-bottom: 1rem;\r\n");
      out.write("            margin-top: -1px;\r\n");
      out.write("            overflow-x: auto;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("            -webkit-overflow-scrolling: touch;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bd-mode-toggle .dropdown-menu .active .bi {\r\n");
      out.write("            display: block !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("          .active {\r\n");
      out.write(" 			 color: #FFFFFF;\r\n");
      out.write("		}\r\n");
      out.write("    </style>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    $(function(){\r\n");
      out.write("\r\n");
      out.write("     	$(\"#answer\").click(function(event){\r\n");
      out.write("             event.preventDefault();\r\n");
      out.write("            movePage('u');\r\n");
      out.write("		});//click\r\n");
      out.write("\r\n");
      out.write("        $(\"#confirm\").click(function (event) {\r\n");
      out.write("            event.preventDefault();\r\n");
      out.write("            movePage();\r\n");
      out.write("        });\r\n");
      out.write("     	$(\"#cancel\").click(function(event){\r\n");
      out.write("            event.preventDefault();\r\n");
      out.write("            movePage('d')\r\n");
      out.write("     	});//click\r\n");
      out.write("    });//ready\r\n");
      out.write("\r\n");
      out.write("    function movePage(flag) {\r\n");
      out.write("        let name_flag = validateName();\r\n");
      out.write("        let pass_flag = validatePhone();\r\n");
      out.write("        if(pass_flag===true && name_flag){\r\n");
      out.write("          if(flag ==='u'){\r\n");
      out.write("               document.customerFrm.action=\"http://paiks.sist.co.kr/manage/customer/update_customer.jsp\";\r\n");
      out.write("               $(\"#customerFrm\").submit();\r\n");
      out.write("               return;\r\n");
      out.write("           }\r\n");
      out.write("          if(flag ==='d'){\r\n");
      out.write("             let actionText = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cVO.cusFlag}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" === 'Y' ? '활동' : '비활동';\r\n");
      out.write("\r\n");
      out.write("             if(confirm(`[ ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cVO.cusId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" ] 유저를 정말 `+actionText+ `으로 변경하시겠습니까?`)){\r\n");
      out.write("                document.customerFrm.action=\"http://paiks.sist.co.kr/manage/customer/delete_customer.jsp?cusId=");
      out.print(cusId);
      out.write("\";\r\n");
      out.write("                $(\"#customerFrm\").submit();\r\n");
      out.write("            }\r\n");
      out.write("             return;\r\n");
      out.write("         }\r\n");
      out.write("          location.href=\"http://paiks.sist.co.kr/manage/customer/list_customer.jsp?currentPage=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.currentPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function validateName() {\r\n");
      out.write("        var nameFlag = true;\r\n");
      out.write("        var name = $(\"#name\").val().trim();\r\n");
      out.write("        if (name === \"\") {\r\n");
      out.write("            alert(\"이름은 공백이 될 수 없습니다.\");\r\n");
      out.write("            nameFlag = false\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        return nameFlag;\r\n");
      out.write("    }//validateName()\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     function validatePhone(){\r\n");
      out.write("        var passFlag = true;\r\n");
      out.write("\r\n");
      out.write("        var phone = $(\"#phone\").val().trim();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        var phoneParts = phone.split(\"-\");\r\n");
      out.write("\r\n");
      out.write("        if (phone.replace(/[^0-9-]/g, \"\").length !== 13) {\r\n");
      out.write("            alert(\"휴대폰 번호는 '010-1234-5678' 형식이어야 합니다.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        var phone1 = phoneParts[0];\r\n");
      out.write("        var phone2 = phoneParts[1];\r\n");
      out.write("        var phone3 = phoneParts[2];\r\n");
      out.write("\r\n");
      out.write("        if (phone1.length !== 3) {\r\n");
      out.write("            alert(\"휴대폰 번호 첫 번째 자리는 숫자 3자리여야 합니다.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (phone2.length !== 4) {\r\n");
      out.write("            alert(\"휴대폰 번호 중간 자리는 숫자 4자리여야 합니다.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (phone3.length !== 4) {\r\n");
      out.write("            alert(\"휴대폰 번호 마지막 자리는 숫자 4자리여야 합니다.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        return passFlag;\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/svg.jsp", out, false);
      out.write("<!-- svg -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/headbar.jsp", out, false);
      out.write("<!-- headbar -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary\" style=\"height: 900px\">\r\n");
      out.write("            <div class=\"offcanvas-md offcanvas-end bg-body-tertiary\" tabindex=\"-1\" id=\"sidebarMenu\" aria-labelledby=\"sidebarMenuLabel\">\r\n");
      out.write("                <div class=\"offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto\">\r\n");
      out.write("                    <ul class=\"nav nav-pills flex-column\">\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link d-flex align-items-center gap-2\" aria-current=\"page\" href=\"http://paiks.sist.co.kr/manage/dashboard/dashboard.jsp\">\r\n");
      out.write("                                <i class=\"bi bi-house\"></i>\r\n");
      out.write("                                관리자 대시보드\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link d-flex align-items-center gap-2\" href=\"http://paiks.sist.co.kr/manage/menu/selectCoffeeList.jsp\">\r\n");
      out.write("                                <svg class=\"bi\"><use xlink:href=\"#cup-hot\"/></svg>\r\n");
      out.write("                                음료 관리\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link d-flex align-items-center gap-2\" href=\"http://paiks.sist.co.kr/manage/menu/selectDessertList.jsp\">\r\n");
      out.write("                                <svg class=\"bi\"><use xlink:href=\"#cake\"/></svg>\r\n");
      out.write("                                디저트&아이스크림 관리\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link d-flex align-items-center gap-2\" href=\"http://paiks.sist.co.kr/manage/order/selectNotReceivedOrderList.jsp\">\r\n");
      out.write("                                <i class=\"bi bi-cart\"></i>\r\n");
      out.write("                                주문 관리\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link d-flex align-items-center gap-2 active\" href=\"http://paiks.sist.co.kr/manage/customer/list_customer.jsp\">\r\n");
      out.write("                                <i class=\"bi bi-people\"></i>\r\n");
      out.write("                                회원 관리\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <!-- <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link d-flex align-items-center gap-2\" href=\"http://paiks.sist.co.kr/manage/voc/getListCustomSound.jsp\">\r\n");
      out.write("                                <i class=\"bi bi-file-earmark-bar-graph\"></i>\r\n");
      out.write("                                고객의 소리\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li> -->\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <hr class=\"my-3\">\r\n");
      out.write("                    <ul class=\"nav flex-column mb-auto\">\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link d-flex align-items-center gap-2\" href=\"http://paiks.sist.co.kr/manage/logout.jsp\">\r\n");
      out.write("                                <svg class=\"bi\"><use xlink:href=\"#door-closed\"/></svg>\r\n");
      out.write("                                로그아웃\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <main class=\"col-md-9 ms-sm-auto col-lg-10 px-md-4\">\r\n");
      out.write("            <div class=\"d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom\">\r\n");
      out.write("                <h1 class=\"h2\" style=\"font-weight: bold;\">회원 상세보기</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"\" method=\"post\" name=\"customerFrm\" id=\"customerFrm\">\r\n");
      out.write("                <label for=\"cusId\">ID:</label>\r\n");
      out.write("                <input type=\"text\" id=\"cusId\" name=\"cusId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cVO.cusId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("                <input type=\"hidden\" id=\"currentPage\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.currentPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\r\n");
      out.write("                <label for=\"name\">이름:</label>\r\n");
      out.write("                <input type=\"text\" id=\"name\" name=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dd.decrypt(cVO.name)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("                <label for=\"email\">이메일:</label>\r\n");
      out.write("                <input type=\"email\" id=\"email\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dd.decrypt(cVO.email)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("                <label for=\"inputDate\">가입일:</label>\r\n");
      out.write("                <input type=\"date\" id=\"inputDate\" value=\"");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("\" readonly>\r\n");
      out.write("\r\n");
      out.write("                <label for=\"grade\">회원 등급:</label>\r\n");
      out.write("                <select id=\"grade\" name=\"grade\" required>\r\n");
      out.write("                    ");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /manage/customer/detail_customer.jsp(256,20) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems(Grade.values());
        // /manage/customer/detail_customer.jsp(256,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("gradeOption");
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("<option value=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gradeOption.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write('"');
              out.write(' ');
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cVO.grade == gradeOption ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write(">\r\n");
              out.write("                                ");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gradeOption}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</option>\r\n");
              out.write("                    ");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
      }
      out.write("</select>\r\n");
      out.write("                <input type=\"radio\" id=\"status1\" name=\"cusFlag\" value=\"N\" style=\"text-align: left; width: 5%\"  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cVO.cusFlag == 'N'? 'checked': 'disabled'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">활동\r\n");
      out.write("                <input type=\"radio\" id=\"status2\" name=\"cusFlag\" value=\"Y\" style=\"text-align: left; width: 5%\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cVO.cusFlag == 'Y'? 'checked': 'disabled'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">비활동\r\n");
      out.write("                <input type=\"hidden\" id=\"cusFlag\" name=\"Flag\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cVO.cusFlag}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                <label for=\"phone\">전화번호:</label>\r\n");
      out.write("                <input type=\"tel\" id=\"phone\" name=\"phone\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dd.decrypt(cVO.phone)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("                <div style=\"text-align: center;\">\r\n");
      out.write("                    <button class=\"confirm\" id=\"confirm\" >확인</button>\r\n");
      out.write("                    <button class=\"answer\" id=\"answer\">수정</button>\r\n");
      out.write("                    <button class=\"cancel\" id=\"cancel\">\r\n");
      out.write("                        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cVO.cusFlag == 'N' ? '비활동' : '활동'}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </main>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /manage/common/jsp/manager_session_chk.jsp(11,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty managerId}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<script type=\"text/javascript\">\r\n");
          out.write("        // 현재 URL 저장\r\n");
          out.write("        localStorage.setItem(\"returnUrl\",\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\");\r\n");
          out.write("        alert(\"이 페이지는 관리자 로그인이 필요한 페이지입니다.\");\r\n");
          out.write("        location.href=\"http://paiks.sist.co.kr/manage/index.jsp\"\r\n");
          out.write("    </script>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /manage/customer/detail_customer.jsp(252,57) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cVO.inputDate}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /manage/customer/detail_customer.jsp(252,57) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }
}
