/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-11-15 03:07:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.customer._00_common.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import paik_prj.paik_prj.customer.paik.CustomVO;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "공통디자인 - 사용자 페이지 header";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("paik_prj.paik_prj.customer.paik.CustomVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

   CustomVO username = (CustomVO)session.getAttribute("userData");   //사용자정보 저장

      out.write("\r\n");
      out.write("<header id=\"header\">\r\n");
      out.write("   <div class=\"in_header\">\r\n");
      out.write("      <div class=\"sub-bg\"></div>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <ul class=\"topbar\">\r\n");
      out.write("            ");
 if(username != null){ 
      out.write("\r\n");
      out.write("               <li><a href=\"http://paiks.sist.co.kr/customer/05.mypage/mypage.jsp\">");
      out.print( username.getName() );
      out.write("님 안녕하세요</a></li>\r\n");
      out.write("               <li><a href=\"http://paiks.sist.co.kr/customer/03.cart/list_order.jsp\">주문현황</a></li>\r\n");
      out.write("               <li><a href=\"http://paiks.sist.co.kr/customer/06.customer/logout.jsp\">로그아웃</a></li>\r\n");
      out.write("            ");
 } else {
      out.write("\r\n");
      out.write("               <li><a href=\"http://paiks.sist.co.kr/customer/06.customer/loginPage.jsp\">로그인</a></li>\r\n");
      out.write("            ");
 }//if~el 
      out.write("\r\n");
      out.write("         </ul>\r\n");
      out.write("         <div class=\"nav_wrap\">\r\n");
      out.write("            <a href=\"http://paiks.sist.co.kr/index.jsp\" class=\"logo\">\r\n");
      out.write("               <img src=\"http://paiks.sist.co.kr/customer/00.common/images/logo-3.png\" alt=\"빽스커피\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"http://paiks.sist.co.kr/index.jsp\" class=\"logo light\">\r\n");
      out.write("               <img src=\"http://paiks.sist.co.kr/customer/00.common/images/logo-4.png\" alt=\"\"빽스커피\"\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"nav\">\r\n");
      out.write("               <div class=\"nav-icon\"><div></div></div>\r\n");
      out.write("               <ul class=\"navbar\">\r\n");
      out.write("               <li class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-95\">\r\n");
      out.write("                  <a href=\"http://paiks.sist.co.kr/customer/01.paik/introduction.jsp\" style=\"margin-right: 50px;\">빽스커피</a>\r\n");
      out.write("                  <ul class=\"sub-menu\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"http://paiks.sist.co.kr/customer/01.paik/introduction.jsp\">빽스커피소개</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"http://paiks.sist.co.kr/customer/01.paik/coffeeStory.jsp\">커피이야기</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                     <a href=\"http://paiks.sist.co.kr/customer/01.paik/educationStory.jsp\">교육이야기</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </li>\r\n");
      out.write("               \r\n");
      out.write("               <li class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-95\">\r\n");
      out.write("                  <a href=\"http://paiks.sist.co.kr/customer/02.menu/newMenuPage.jsp\" style=\"margin-right: 50px;\">메뉴</a>\r\n");
      out.write("                  <ul class=\"sub-menu\">\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a href=\"http://paiks.sist.co.kr/customer/02.menu/newMenuPage.jsp\">신메뉴</a>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a href=\"http://paiks.sist.co.kr/customer/02.menu/coffeeMenuPage.jsp\">커피</a>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a href=\"http://paiks.sist.co.kr/customer/02.menu/drinkMenuPage.jsp\">음료</a>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a href=\"http://paiks.sist.co.kr/customer/02.menu/icecreamDessertMenuPage.jsp\">아이스크림/디저트</a>\r\n");
      out.write("                     </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-95\">\r\n");
      out.write("                  <a href=\"http://paiks.sist.co.kr/customer/03.cart/cart.jsp\" style=\"margin-right: 50px;\">장바구니</a>\r\n");
      out.write("                  <ul class=\"sub-menu\">\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a href=\"http://paiks.sist.co.kr/customer/03.cart/cart.jsp\">장바구니</a>\r\n");
      out.write("                     </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </li>\r\n");
      out.write("               ");
      out.write("\r\n");
      out.write("               <li class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-95\">\r\n");
      out.write("                  <a href=\"http://paiks.sist.co.kr/customer/05.mypage/mypage.jsp\" style=\"margin-right: 180px;\">마이페이지</a>\r\n");
      out.write("                  <ul class=\"sub-menu\">\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a href=\"http://paiks.sist.co.kr/customer/05.mypage/mypage.jsp\">마이페이지</a>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a href=\"http://paiks.sist.co.kr/customer/05.mypage/chkPass.jsp\">비밀번호변경</a>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a href=\"http://paiks.sist.co.kr/customer/05.mypage/modify.jsp\">개인정보변경</a>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a href=\"http://paiks.sist.co.kr/customer/05.mypage/deleteAccount.jsp\">회원탈퇴</a>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a href=\"http://paiks.sist.co.kr/customer/03.cart/list_order.jsp\">주문현황(내역)</a>\r\n");
      out.write("                     </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</header>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
