/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-11-15 03:10:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.customer._01_paik;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class coffeeStory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "빽스커피 - 커피이야기화면";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("    \r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/customer/05.mypage/remove_password_verified.jsp", out, false);
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko-KR\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"http://paiks.sist.co.kr/customer/00.common/images/btnImg.png\">\r\n");
      out.write("\r\n");
      out.write("<title>빽스커피  :::  커피이야기</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" id=\"theme-css-style-css\" href=\"https://paikdabang.com/wp-content/themes/paikdabang/assets/css/paiks_style.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\" id=\"theme-css-style-css\"  href=\"https://paikdabang.com/wp-content/themes/paikdabang/assets/css/style.css?ver=4.9.4\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"icon\" href=\"http://paiks.sist.co.kr/customer/00.common/images/favicon32x32.png\" sizes=\"32x32\" />\r\n");
      out.write("<link rel=\"icon\" href=\"http://paiks.sist.co.kr/customer/00.common/images/favicon192x192.png\" sizes=\"192x192\" />\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" href=\"http://paiks.sist.co.kr/customer/00.common/images/favicon180x180.png\" />\r\n");
      out.write("<meta name=\"msapplication-TileImage\" content=\"http://paiks.sist.co.kr/customer/00.common/images/favicon270x270.png\" />\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("	\r\n");
      out.write("});//ready()\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"header\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/customer/00.common/jsp/header.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("jQuery(document).ready(function(){\r\n");
      out.write("    jQuery('.menu-item-1019 a').attr('target','_blank');\r\n");
      out.write("    jQuery('.menu-item-17246 a').attr('target','_blank');\r\n");
      out.write("    jQuery('.menu-item-17247 a').attr('target','_blank');\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"content-wrap\">\r\n");
      out.write("<div id=\"primary\" class=\"content-area\">\r\n");
      out.write("<main id=\"main\" class=\"site-main\" role=\"main\">\r\n");
      out.write("<article id=\"post-17629\" class=\"post-17629 page type-page status-publish hentry\">\r\n");
      out.write("<div class=\"entry-content\">\r\n");
      out.write("<div class=\"coffee_story\">\r\n");
      out.write("	<div class=\"story_con\">\r\n");
      out.write("		<div class=\"txt_wrap\">\r\n");
      out.write("			<h1>PAIK’S COFFEE STORY</h1>\r\n");
      out.write("			<img src=\"http://paiks.sist.co.kr/customer/01.paik/images/about1.png\" />\r\n");
      out.write("			<dl>\r\n");
      out.write("				<dt>자연이 키운 커피</dt>\r\n");
      out.write("				<dd>빽스커피 시그니처 블렌딩</dd>\r\n");
      out.write("			</dl>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"ytb_wrap\">\r\n");
      out.write("			<iframe width=\"100%\" src=\"https://www.youtube.com/embed/1-zO9VZgAuw\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"quality_con\">\r\n");
      out.write("		<h2 class=\"con_tt\">Coffee Bean Quality <span class=\"block_txt\">&amp; Processing</span></h2>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li>\r\n");
      out.write("				<div class=\"img_wrap\"><img src=\"http://paiks.sist.co.kr/customer/01.paik/images/story_img01.jpg\" alt=\"SPECIALTY COFFEE BLENDING\" /></div>\r\n");
      out.write("				<div class=\"txt_wrap\">\r\n");
      out.write("					<h3>SPECIALTY <span class=\"block_txt\">COFFEE BLENDING</span></h3>\r\n");
      out.write("					<dl>\r\n");
      out.write("						<dt>빽스커피에서 만나는 <em>고품질의 커피</em></dt>\r\n");
      out.write("						<dd>산지의 특징이 명확하고, 향미가 뛰어나며, <span class=\"block_txt\">극소량만 생산되는 최고등급의 스페셜티 커피</span> 원두를 활용하여 블렌딩했습니다.</dd>\r\n");
      out.write("						<dd class=\"note_txt\"><em>*스페셜티 커피란?</em>미국 스페셜티 커피 협회(SCAA)의 평가에서 80점 이상을 받은 우수등급의 커피입니다.</dd>\r\n");
      out.write("					</dl>\r\n");
      out.write("				</div>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li>\r\n");
      out.write("				<div class=\"img_wrap\"><img src=\"http://paiks.sist.co.kr/customer/01.paik/images/story_img02.jpg\" alt=\"VELOSO COFFEE\" /></div>\r\n");
      out.write("				<div class=\"txt_wrap\">\r\n");
      out.write("					<h3>VELOSO COFFEE</h3>\r\n");
      out.write("					<dl>\r\n");
      out.write("						<dt>좋은 토양에서 자라 온 <em>빽스커피의 커피</em></dt>\r\n");
      out.write("						<dd>빽스커피는 고품질 커피 원산지로 인정받고 있는 <span class=\"block_txt\">브라질의 벨로소 농장에서 생산된 원두를 사용합니다.</span> 좋은 토양에서 자란 커피 체리가 만들어내는 <span class=\"block_txt\">신선하고 풍부한 향미를 즐겨보세요.</span></dd>\r\n");
      out.write("					</dl>\r\n");
      out.write("				</div>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li>\r\n");
      out.write("				<div class=\"img_wrap\"><img src=\"http://paiks.sist.co.kr/customer/01.paik/images/story_img03.jpg\" alt=\"NEW CROP COFFEE BEANS\" /></div>\r\n");
      out.write("				<div class=\"txt_wrap\">\r\n");
      out.write("					<h3>NEW CROP <span class=\"block_txt\">COFFEE BEANS</span></h3>\r\n");
      out.write("					<dl>\r\n");
      out.write("						<dt>신선함이 살아있는 <em>빽스커피의 커피</em></dt>\r\n");
      out.write("						<dd>수확한지 1년 미만의 햇생두, <span class=\"block_txt\">뉴크롭원두를 사용하여 신선함이 살아있습니다.</span></dd>\r\n");
      out.write("					</dl>\r\n");
      out.write("				</div>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li>\r\n");
      out.write("				<div class=\"img_wrap\"><img src=\"http://paiks.sist.co.kr/customer/01.paik/images/story_img04.jpg\" alt=\"DOT(Dried On Tree) PROCESSING\" /></div>\r\n");
      out.write("				<div class=\"txt_wrap\">\r\n");
      out.write("					<h3>DOT<p>(Dried On Tree)</p><span class=\"block_txt\">PROCESSING</span></h3>\r\n");
      out.write("					<dl>\r\n");
      out.write("						<dt>커피 본연의 맛이 느껴지는 <em>빽스커피의 커피</em></dt>\r\n");
      out.write("						<dd>DOT 프로세싱으로 커피의 단맛과 향미가 한층 더 도드라져, <span class=\"block_txt\">커피 본연의 맛을 더 풍부하게 느낄 수 있습니다.</span></dd>\r\n");
      out.write("						<dd class=\"note_txt\"><em>*DOT 프로세싱이란?</em>커피체리를 바로 수확하지 않고 나무에서 건조해 단맛을 충분하게 입히는 방식입니다.</dd>\r\n");
      out.write("					</dl>\r\n");
      out.write("				</div>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"cupping_con\">\r\n");
      out.write("		<h2 class=\"con_tt\">PAIK’S Coffee <span class=\"block_txt\">Cupping Note</span></h2>\r\n");
      out.write("		<div class=\"cupp_con\">\r\n");
      out.write("			<p class=\"con_txt\">브라질 원두 고유의 묵직한 바디감이 느껴지며, <span class=\"block_txt\">아몬드의 고소함과 밀크초콜릿의 은은한 단맛이 균형을 이루는 매력적인 맛입니다.</span> 커피를 머금었을 때 느껴지는 부드러운 실키함을 느껴보세요!</p>\r\n");
      out.write("			<ul class=\"cupping_icon\">\r\n");
      out.write("				<li><span></span><p>Chocolate</p></li>\r\n");
      out.write("				<li><span></span><p>Cacao Bean</p></li>\r\n");
      out.write("				<li><span></span><p>Almond</p></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"taste_con\">\r\n");
      out.write("			<h3>PAIK’S COFFEE TASTE</h3>\r\n");
      out.write("			<div class=\"taste_bar\">\r\n");
      out.write("				<div class=\"bar_txt_mo\"><span>L</span><span>M</span><span>H</span></div>\r\n");
      out.write("				<div class=\"bar_txt\"><span>Light</span><span>Medium</span><span>High</span></div>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li>\r\n");
      out.write("						<p>단맛</p>\r\n");
      out.write("						<div class=\"bar_graph\"><span class=\"on\"></span><span class=\"on\"></span><span class=\"on\"></span><span class=\"on\"></span><span></span></div>\r\n");
      out.write("					</li>\r\n");
      out.write("					\r\n");
      out.write("					<li>\r\n");
      out.write("						<p>신맛</p>\r\n");
      out.write("						<div class=\"bar_graph\"><span class=\"on\"></span><span class=\"on\"></span><span></span><span></span><span></span></div>\r\n");
      out.write("					</li>\r\n");
      out.write("					\r\n");
      out.write("					<li>\r\n");
      out.write("						<p>쓴맛</p>\r\n");
      out.write("						<div class=\"bar_graph\"><span class=\"on\"></span><span class=\"on\"></span><span class=\"on\"></span><span></span><span></span></div>\r\n");
      out.write("					</li>\r\n");
      out.write("					\r\n");
      out.write("					<li>\r\n");
      out.write("						<p>바디감</p>\r\n");
      out.write("						<div class=\"bar_graph\"><span class=\"on\"></span><span class=\"on\"></span><span class=\"on\"></span><span class=\"on\"></span><span></span></div>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"roasting_con\">\r\n");
      out.write("			<h3>ROASTING POINT</h3>\r\n");
      out.write("			<div class=\"roasting_bar\">\r\n");
      out.write("				<div class=\"bar_txt_mo\"><span>L</span><span>M</span><span>D</span></div>\r\n");
      out.write("				<div class=\"bar_txt\"><span>Light</span><span>Medium</span><span>Dark</span></div>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><p>Medium<p><span>MD</span></li>\r\n");
      out.write("					<li><p>High<p><span>HI</span></li>\r\n");
      out.write("					<li><p>City<p><span>CT</span></li>\r\n");
      out.write("					<li class=\"on\"><p>Full City<p><span>FC</span></li>\r\n");
      out.write("					<li class=\"on\"><p>French<p><span>FR</span></li>\r\n");
      out.write("					<li><p>Italian<p><span>IT</span></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"signature_con\">\r\n");
      out.write("		<h2 class=\"con_tt\">PAIK’S Coffee <span class=\"block_txt\">Signature</span></h2>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li>\r\n");
      out.write("				<div class=\"pro_img\"><img src=\"http://paiks.sist.co.kr/customer/01.paik/images/story_pro01.jpg\" alt=\"아메리카노\" /></div>\r\n");
      out.write("				<dl>\r\n");
      out.write("					<dt>아메리카노</dt>\r\n");
      out.write("					<dd>빽스커피의 시그니처 블렌딩으로 깊고 진한 맛의 아메리카노</dd>\r\n");
      out.write("				</dl>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li>\r\n");
      out.write("				<div class=\"pro_img\"><img src=\"http://paiks.sist.co.kr/customer/01.paik/images/story_pro02.jpg\" alt=\"빽's 카페라떼\" /></div>\r\n");
      out.write("				<dl>\r\n");
      out.write("					<dt>빽’s 카페라떼</dt>\r\n");
      out.write("					<dd>진한 에스프레소와 우유가 어우러진 부드러운 빽스커피 라떼. HOT의 경우 생크림이 첨가되어 고소하고 부드러운 맛이 업그레이드 됩니다.</dd>\r\n");
      out.write("				</dl>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li>\r\n");
      out.write("				<div class=\"pro_img\"><img src=\"http://paiks.sist.co.kr/customer/01.paik/images/story_pro03.jpg\" alt=\"아샷추\" /></div>\r\n");
      out.write("				<dl>\r\n");
      out.write("					<dt>아샷추</dt>\r\n");
      out.write("					<dd>복숭아맛 아이스티에 에스프레소샷을 추가해 달콤함과 쌉쌀함이 공존하는 매력적인 맛</dd>\r\n");
      out.write("				</dl>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li>\r\n");
      out.write("				<div class=\"pro_img\"><img src=\"http://paiks.sist.co.kr/customer/01.paik/images/story_pro04.jpg\" alt=\"원조커피\" /></div>\r\n");
      out.write("				<dl>\r\n");
      out.write("					<dt>원조커피</dt>\r\n");
      out.write("					<dd>익숙한 듯 색다른 믹스커피 업그레이드 버전. 빽스커피만의 시그니처 커피메뉴</dd>\r\n");
      out.write("				</dl>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</article>\r\n");
      out.write("</main>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/customer/00.common/jsp/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
