/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-11-15 03:07:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.customer._01_paik;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class introduction_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "빽스커피소개 화면";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/customer/05.mypage/remove_password_verified.jsp", out, false);
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko-KR\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"http://paiks.sist.co.kr/customer/00.common/images/btnImg.png\">\r\n");
      out.write("\r\n");
      out.write("<title>빽스커피  :::  빽스커피소개</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" id=\"theme-css-style-css\" href=\"https://paikdabang.com/wp-content/themes/paikdabang/assets/css/paiks_style.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\" id=\"theme-css-style-css\"  href=\"https://paikdabang.com/wp-content/themes/paikdabang/assets/css/style.css?ver=4.9.4\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"icon\" href=\"http://paiks.sist.co.kr/customer/00.common/images/favicon32x32.png\" sizes=\"32x32\" />\r\n");
      out.write("<link rel=\"icon\" href=\"http://paiks.sist.co.kr/customer/00.common/images/favicon192x192.png\" sizes=\"192x192\" />\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" href=\"http://paiks.sist.co.kr/customer/00.common/images/favicon180x180.png\" />\r\n");
      out.write("<meta name=\"msapplication-TileImage\" content=\"http://paiks.sist.co.kr/customer/00.common/images/favicon270x270.png\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("	\r\n");
      out.write("});//ready()\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"header\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/customer/00.common/jsp/header.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("jQuery(document).ready(function(){\r\n");
      out.write("    jQuery('.menu-item-1019 a').attr('target','_blank');\r\n");
      out.write("    jQuery('.menu-item-17246 a').attr('target','_blank');\r\n");
      out.write("    jQuery('.menu-item-17247 a').attr('target','_blank');\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"content-wrap\">\r\n");
      out.write("<div id=\"primary\" class=\"content-area\">\r\n");
      out.write("<main id=\"main\" class=\"site-main\" role=\"main\">\r\n");
      out.write("		\r\n");
      out.write("<article id=\"post-17721\" class=\"post-17721 page type-page status-publish hentry\">\r\n");
      out.write("<div class=\"entry-content\">\r\n");
      out.write("<p>");
      out.write("</p>\r\n");
      out.write("	<div class=\"sub_visual bg-paik\">\r\n");
      out.write("	<div class=\"txt\">\r\n");
      out.write("		<h1>빽스커피</h1>\r\n");
      out.write("		<p>합리적인 가격, 놀라운 퀄리티의 커피전문점 &#8220;빽스커피&#8221;입니다.</p>\r\n");
      out.write("	</div>\r\n");
      out.write("	<ul class=\"page_tab st-2\">\r\n");
      out.write("		<li class=\"on\"><a href=\"http://paiks.sist.co.kr/customer/01.paik/introduction.jsp\">빽스커피 소개</a></li>\r\n");
      out.write("		<li><a href=\"http://paiks.sist.co.kr/customer/01.paik/coffeeStory.jsp\">커피 이야기</a></li>\r\n");
      out.write("		<li><a href=\"http://paiks.sist.co.kr/customer/01.paik/educationStory.jsp\">교육 이야기</a></li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("<p>");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<div class=\"about_paiks\">\r\n");
      out.write("	<div class=\"identifire_con\">\r\n");
      out.write("		<h2 class=\"con_tt\">BRAND IDENTIFIER</h2>\r\n");
      out.write("		<dl class=\"sub_tt\">\r\n");
      out.write("			<dt>\r\n");
      out.write("				<span>PRIMARY IDENTIFIER</span>\r\n");
      out.write("				<p>빽스커피 브랜드 규정</p>\r\n");
      out.write("			</dt>\r\n");
      out.write("			<dd>\r\n");
      out.write("				<p>빽스커피 <em>Idenfitire</em>는 빽스커피를 대표하는 중요한 상징요소로, 심볼마크와 로고타입의 조합을 의미합니다.</p>\r\n");
      out.write("				<p>빽스커피의 시각 아이덴티티 구축은 정확한 <em>Identifier</em> 규정에 따라야 하며, <span class=\"block_txt\">어떠한 경우에도 훼손, 변형 등의 이미지 손상을 가해서는 안됩니다.</span></p>\r\n");
      out.write("			</dd>\r\n");
      out.write("		</dl>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"logo_con\">\r\n");
      out.write("			<div class=\"standard_logo\">\r\n");
      out.write("				<p><img src=\"http://paiks.sist.co.kr/customer/01.paik/images/standard_logo.png\" alt=\"빽스커피\" /></p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<ul class=\"logo_li\">\r\n");
      out.write("				<li><img src=\"http://paiks.sist.co.kr/customer/01.paik/images/paiks_logo01.jpg\" alt=\"PAIK'S COFFEE\" /></li>\r\n");
      out.write("				<li><img src=\"http://paiks.sist.co.kr/customer/01.paik/images/paiks_logo02.jpg\" alt=\"빽스커피\" /></li>\r\n");
      out.write("				<li><img src=\"http://paiks.sist.co.kr/customer/01.paik/images/paiks_logo03.jpg\" alt=\"PAIK'S COFFEE\" /></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"color_con\">\r\n");
      out.write("		<dl class=\"sub_tt\">\r\n");
      out.write("			<dt>\r\n");
      out.write("				<span>BRAND COLOR</span>\r\n");
      out.write("				<p>빽스커피 컬러 시스템</p>\r\n");
      out.write("			</dt>\r\n");
      out.write("		</dl>\r\n");
      out.write("	\r\n");
      out.write("		<ul class=\"paiks_color\">\r\n");
      out.write("			<li>\r\n");
      out.write("				<div class=\"color_box\"></div>\r\n");
      out.write("				<dl>\r\n");
      out.write("					<dt>PAIK&#8217;S NAVY BLUE</dt>\r\n");
      out.write("					<dd>\r\n");
      out.write("						<p>CMYK : C100 / M98 / Y58 / K14</p>\r\n");
      out.write("						<p>RGB : G31 / B96</p>\r\n");
      out.write("						<p>#001F60</p>\r\n");
      out.write("					</dd>\r\n");
      out.write("				</dl>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li>\r\n");
      out.write("				<div class=\"color_box\"></div>\r\n");
      out.write("				<dl>\r\n");
      out.write("					<dt>PAIK&#8217;S YELLOW</dt>\r\n");
      out.write("					<dd>\r\n");
      out.write("						<p>CMYK : M11 / Y87</p>\r\n");
      out.write("						<p>RGB : R255 / G232</p>\r\n");
      out.write("						<p>#FFE800</p>\r\n");
      out.write("					</dd>\r\n");
      out.write("				</dl>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li>\r\n");
      out.write("				<div class=\"color_box\"></div>\r\n");
      out.write("				<dl>\r\n");
      out.write("					<dt>PAIK&#8217;S LIGHT GRAY</dt>\r\n");
      out.write("					<dd>\r\n");
      out.write("						<p>CMYK : K10</p>\r\n");
      out.write("						<p>RGB : R230 / G231 / B232</p>\r\n");
      out.write("						<p>#E6E7E8</p>\r\n");
      out.write("					</dd>\r\n");
      out.write("				</dl>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"color_logo\">\r\n");
      out.write("			<dl>\r\n");
      out.write("			<dt>WHITE BACKGROUND / NAVY COLOR</dt>\r\n");
      out.write("			<dd><img src=\"http://paiks.sist.co.kr/customer/01.paik/images/color_logo01.jpg\" alt=\"PAIK'S COFFEE\" /></dd>\r\n");
      out.write("			</dl>\r\n");
      out.write("			<dl>\r\n");
      out.write("			<dt>WHITE BACKGROUND / BLACK COLOR</dt>\r\n");
      out.write("			<dd><img src=\"http://paiks.sist.co.kr/customer/01.paik/images/color_logo02.jpg\" alt=\"PAIK'S COFFEE\" /></dd>\r\n");
      out.write("			</dl>\r\n");
      out.write("			<dl>\r\n");
      out.write("			<dt>YELLOW BACKGROUND / NAVY COLOR</dt>\r\n");
      out.write("			<dd><img src=\"http://paiks.sist.co.kr/customer/01.paik/images/color_logo03.jpg\" alt=\"PAIK'S COFFEE\" /></dd>\r\n");
      out.write("			</dl>\r\n");
      out.write("			<dl>\r\n");
      out.write("			<dt>NAVY BACKGROUND / YELLOW COLOR</dt>\r\n");
      out.write("			<dd><img src=\"http://paiks.sist.co.kr/customer/01.paik/images/color_logo04.jpg\" alt=\"PAIK'S COFFEE\" /></dd>\r\n");
      out.write("			</dl>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"value_con\">\r\n");
      out.write("		<h2 class=\"con_tt\">빽스커피의 핵심가치</h2>\r\n");
      out.write("		<ul class=\"value_li\">\r\n");
      out.write("			<li>\r\n");
      out.write("				<div class=\"value_icon\"></div>\r\n");
      out.write("				<dl>\r\n");
      out.write("					<dt>동반성장</dt>\r\n");
      out.write("					<dd>본사와 가맹점주가 상생할 수 있는 경영방침을 추구합니다.<br /><em>안정적이고 건강한 가맹점을 육성</em>하여 오래도록 함께 합니다.</dd>\r\n");
      out.write("				</dl>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li>\r\n");
      out.write("				<div class=\"value_icon\"></div>\r\n");
      out.write("				<dl>\r\n");
      out.write("					<dt>소통</dt>\r\n");
      out.write("					<dd>각 분기별로 지역별 소규모 간담회를 진행하고, <span class=\"block_txt\">매년 말 전체 점주님을 대상으로 하는 점주연수를 진행합니다.</span> <em>가맹본부가 발전할 수 있는 방향성에 대해 함께 논의하며 토론</em>합니다.</dd>\r\n");
      out.write("				</dl>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li>\r\n");
      out.write("				<div class=\"value_icon\"></div>\r\n");
      out.write("				<dl>\r\n");
      out.write("					<dt>고객만족도</dt>\r\n");
      out.write("					<dd>유통과정에서 발생하는 가맹본부의 수익을 최소화하여, <span class=\"block_txt\">고급 식자재를 사용하되 합리적인 가격을 유지하고, <em>만족도 높은 서비스를 제공</em>합니다.</span></dd>\r\n");
      out.write("				</dl>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"trend_con\">\r\n");
      out.write("		<h2 class=\"con_tt\">발 빠른 트렌드 리딩</h2>\r\n");
      out.write("		<ul class=\"trend_li\">\r\n");
      out.write("			<li>\r\n");
      out.write("				<div class=\"img_con\"><img src=\"http://paiks.sist.co.kr/customer/01.paik/images/trend_img01.jpg\" alt=\"다양한 맛과 비주얼의 시그니처 커피메뉴\" /></div>\r\n");
      out.write("				<dl class=\"sub_tt\">\r\n");
      out.write("					<dt>\r\n");
      out.write("					<span>SIGNATURE COFFEE MENU</span>\r\n");
      out.write("					<p>다양한 맛과 비주얼의 <span class=\"block_txt\">시그니처 커피메뉴</span></p>\r\n");
      out.write("					</dt>\r\n");
      out.write("					<dd>\r\n");
      out.write("					<p>퀄리티 높은 커피를 다양한 맛과 비주얼로 <span class=\"block_txt\">고객들에게 제공하여 달달연유라떼, 아샷추 등의</span> <em>빽스커피 시그니처 커피메뉴로 안착</em>시켰습니다.</p>\r\n");
      out.write("					</dd>\r\n");
      out.write("				</dl>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li>\r\n");
      out.write("				<div class=\"img_con\"><img src=\"http://paiks.sist.co.kr/customer/01.paik/images/trend_img02.jpg\" alt=\"다시 돌아오는 계속 생각나는 그 음료\" /></div>\r\n");
      out.write("				<dl class=\"sub_tt\">\r\n");
      out.write("					<dt>\r\n");
      out.write("						<span>SEASON BACK DRINK</span>\r\n");
      out.write("						<p>다시 돌아오는 <span class=\"block_txt\">계속 생각나는 그 음료</span></p>\r\n");
      out.write("					</dt>\r\n");
      out.write("					<dd>\r\n");
      out.write("						<p>고객들이 즐겨 마셨던 시그널한 메뉴들을 재출시하며, <span class=\"block_txt\">끊임없이 생각나는 브랜드로 자리잡았습니다.</span></p>\r\n");
      out.write("						<p>부담 없이 들를 수 있는 <em>합리적인 가격에 트렌디하고 맛있는 음료가 항상 반겨주는 빽스커피</em>가 되겠습니다.</p>\r\n");
      out.write("					</dd>\r\n");
      out.write("				</dl>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</article>\r\n");
      out.write("</main>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/customer/00.common/jsp/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>wrap\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
